########################################
# Utilities
# -------------------------------------
# Just plugins useful I think.
########################################

[[plugins]]
lazy = true
on_event = 'VimEnter'
repo = 'vim-jp/vimdoc-ja'

